export const Strings = {
    LOOK_UP_INSURNACE: "Look up your insurance",
    EDGE_COMP_PROVIDERS: "EdgePark is compatible with major insurance providers",
    YOUR_SHIP_ADD: "Your shipping address",
    SHIP_RIGHT_TO_DOOR: "We ship your medications right to your door. \n Where would you like to recieve your first shipment?",
    STREET_ADD_1: "Street Address 1",
    STREET_ADD_2: "Street Address 2",
    ZIP_CD: "ZIP Code",
    CITY: "City",
    STATE: "State",
    ABOUT_YOU: "About you",
    MORE_INFO_ABOUT_YOU: "As we are new pharmacy, we need more info about you & your health. \n We only use this information, so that we can serve you better",
    ADD_YOUR_DOCTORS: "Add your doctors",
    REACH_OUT_TO_DOCS: "We reach out to your doctors, to verify the details.",
    GET_STARTED_PHARMACY: "Get started on leading a more stress free life. Simple pharmacy.",
    GET_STARTED: "Get Started",
    LEGAL_FIRST_NAME: "Legal First Name",
    LEGAL_LAST_NAME: "Legal Last Name",
    EMAIL_ADDRESS: "Legal Email Address",
    PASSWORD: "Password",
    PHONE_NUMBER: "Phone number",
    HOW_DID_YOU_HEAR_EDGEPARK: "How did you hear about edgepark?",
    SIGNING_UP_TO_EDGEPARK: "Signing up on edgepark (00:40)"
}